name: Release Production

on:
  push:
    tags:
      - v*
  workflow_dispatch: {}

jobs:
  build_android_production:
    name: Build Android (production)
    type: build
    params:
      platform: android
      profile: production

  build_ios_production:
    name: Build iOS (production)
    type: build
    params:
      platform: ios
      profile: production

  approve_submit:
    name: Approve Store Submission
    type: require-approval
    needs:
      - build_android_production
      - build_ios_production

  submit_android:
    name: Submit Android
    type: submit
    needs:
      - approve_submit
      - build_android_production
    params:
      build_id: ${{ needs.build_android_production.outputs.build_id }}
      profile: production

  submit_ios:
    name: Submit iOS
    type: submit
    needs:
      - approve_submit
      - build_ios_production
    params:
      build_id: ${{ needs.build_ios_production.outputs.build_id }}
      profile: production
